INSERT INTO PRODUCT (PRODUCT_ID, CATEGORY, DESCRIPTION, IMAGE_NAME, PRICE, PRODUCT_TITLE) VALUES 
(1, 'Electronics', 'Over-ear noise-cancelling headphones with 30h battery', 'logo', 79.99, 'Wireless Bluetooth Headphones'),
(2, 'Accessories', 'Shockproof transparent case with MagSafe support', 'logo', 29.99, 'iPhone 15 Pro Case - Clear'),
(3, 'Wearables', 'Heart rate, sleep tracking & waterproof design', 'logo', 149.99, 'Smart Watch Fitness Tracker'),
(4, 'Electronics', 'Compact charger with GaN technology', 'logo', 39.99, 'USB-C Fast Charger 65W'),
(5, 'Fashion', 'Soft cotton blend hoodie - perfect for casual wear', 'logo', 49.99, 'Women''s Oversized Hoodie'),
(6, 'Fashion', 'Stretch denim with modern slim cut', 'logo', 59.99, 'Men''s Slim Fit Jeans - Black'),
(7, 'Beauty', 'Brightening & anti-aging face serum', 'logo', 32.99, 'Vitamin C Serum 30ml'),
(8, 'Beauty', 'Lightweight daily cream for all skin types', 'logo', 28.99, 'Hydrating Face Moisturizer'),
(9, 'Sports', 'Eco-friendly TPE material with carrying strap', 'logo', 39.99, 'Yoga Mat Non-Slip 6mm'),
(10, 'Sports', 'Latex bands with different strength levels', 'logo', 29.99, 'Resistance Bands Set (5pcs)'),
(11, 'Bags', 'Water-resistant with USB charging port', 'logo', 69.99, 'Backpack Laptop Bag 15.6"'),
(12, 'Electronics', 'Ergonomic design, 2.4GHz connection', 'logo', 24.99, 'Wireless Mouse Silent Click'),
(13, 'Electronics', 'Fast charging with dual USB ports', 'logo', 44.99, 'Portable Power Bank 20000mAh'),
(14, 'Fashion', 'Classic aviator style for men & women', 'logo', 39.99, 'Sunglasses Polarized UV400'),
(15, 'Accessories', 'RFID blocking slim wallet - holds 12 cards', 'logo', 42.99, 'Minimalist Leather Wallet'),
(16, 'Health', 'Includes 8 brush heads & travel case', 'logo', 59.99, 'Electric Toothbrush with 5 Modes'),
(17, 'Home Appliances', 'Oil-free cooking with 8 preset programs', 'logo', 119.99, 'Air Fryer 4.5L Digital'),
(18, 'Electronics', 'High-speed wireless router for home use', 'logo', 89.00, 'Dual-Band Wi-Fi 6 Router'),
(19, 'Bags', 'Small crossbody bag for daily essentials', 'logo', 35.50, 'Women''s Crossbody Bag'),
(20, 'Health', 'Digital thermometer with fast reading time', 'logo', 15.99, 'Non-Contact Infrared Thermometer'),
(21, 'Electronics', 'Tactile mechanical switches, RGB backlighting', 'logo', 89.99, 'Mechanical Gaming Keyboard'),
(22, 'Electronics', '27-inch 4K Monitor', 'logo', 199.99, '27-inch 4K Monitor'),
(23, 'Electronics', '15W fast wireless charging pad for smartphones', 'logo', 34.99, 'Qi Wireless Charging Pad'),
(24, 'Electronics', 'Waterproof Bluetooth speaker with 10h battery', 'logo', 49.99, 'Portable Speaker'),
(25, 'Fashion', 'Genuine leather belt with antique silver buckle', 'logo', 39.99, 'Classic Leather Belt'),
(26, 'Fashion', 'Midi length floral print summer dress', 'logo', 69.99, 'Women''s Floral Midi Dress'),
(27, 'Fashion', 'Breathable pique knit polo shirt', 'logo', 29.99, 'Men''s Pique Polo Shirt'),
(28, 'Fashion', 'Soft, oversized cashmere blend winter scarf', 'logo', 45.00, 'Cashmere Blend Scarf'),
(29, 'Beauty', 'Detoxifying clay mask with charcoal and tea tree', 'logo', 19.99, 'Purifying Clay Mask'),
(30, 'Beauty', 'Volumizing Shampoo 400ml', 'logo', 15.50, 'Volumizing Shampoo 400ml'),
(31, 'Beauty', 'Intensive moisturizing hand cream with shea butter', 'logo', 12.99, 'Repairing Hand Cream'),
(32, 'Sports', 'Insulated stainless steel bottle, 24-hour cold', 'logo', 25.99, 'Insulated Water Bottle 32oz'),
(33, 'Sports', 'Set of 10lb Neoprene Dumbbells', 'logo', 49.99, 'Set of 10lb Neoprene Dumbbells'),
(34, 'Sports', 'Padded weightlifting gloves with wrist support', 'logo', 18.99, 'Gym Workout Gloves'),
(35, 'Accessories', 'Luxury rollerball pen set with refill cartridges', 'logo', 35.00, 'Executive Pen Set'),
(36, 'Accessories', 'Compact Key Organizer', 'logo', 19.99, 'Compact Key Organizer'),
(37, 'Accessories', 'Adjustable aluminum stand for 10-inch tablets', 'logo', 29.99, 'Universal Tablet Stand'),
(38, 'Home Appliances', 'Cordless handheld vacuum with cyclonic suction', 'logo', 69.99, 'Portable Handheld Vacuum'),
(39, 'Health', 'High-precision digital scale with BMI tracking', 'logo', 29.99, 'Smart Digital Body Scale'),
(40, 'Bags', 'Large capacity duffel bag, perfect for gym or travel', 'logo', 49.99, 'Large Travel Duffel Bag');